### ISSUE TITLE
Can I use the project for a text to text task?

### ISSUE THREAD

**Issue by puraminy** [HKUNLP/UnifiedSKG#18]
I am interested in using prefix-tuning with t5 implemented in this project, but for a text to text project. (text generation). Could you guide me which files should I follow or how to modify them to add such a task. Or if I just want to use the `prefixtuning` part of the models in my own project, how can I call the model.

**Comment by Timothyxxx** [comment]
Hi,

It could be achieved by our framework. Just add your own task, seq2seq_convertion file and config in [tasks](https://github.com/HKUNLP/UnifiedSKG/tree/main/tasks), [seq2seq_construction](https://github.com/HKUNLP/UnifiedSKG/tree/main/seq2seq_construction) and [configure](https://github.com/HKUNLP/UnifiedSKG/tree/main/configure) file as we showed in [Add a new task into UnifiedSKG](https://github.com/HKUNLP/UnifiedSKG#add-a-new-task-into-unifiedskg) section. It is also recommended to read through the code and check what we did for the FeTaQA or other tasks and #14 if you need more details in running. Feel free to clean the code by yourself.

Hope these information helpful!
Thanks!
