### ISSUE TITLE
How can I specify PLM folder

### ISSUE THREAD

**Issue by puraminy** [HKUNLP/UnifiedSKG#19]
I have problem in downloading or caching the PLM due to my connection and blocked websites.

I want to give the folder of PLM which was already downloaded. How can I set it in ymal?
Thanks

**Comment by puraminy** [comment]
It seems the configuration file accepts file path too:

```
[bert]
location = /home/pouramini/pret/t5-base
```

**Comment by puraminy** [comment]
Now my problem is how can I specify the number of training and test records, I don't want to use whole training records.

**Comment by Timothyxxx** [comment]
Hi,

What do you mean by `number of training and test records` .

Thanks

**Comment by puraminy** [comment]
My dataset have 700,000 training records, but I want to train th emodel on 4000 of them. How can I do that? 

Maybe I should set training steps, anyway I tried a parameter and I get the error:

```
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--num_training_steps', '4000']
```

**Comment by Timothyxxx** [comment]
Sorry, I still don't understand😂. Did you mean you want to control the training epochs/steps?

**Comment by puraminy** [comment]
Yes, to control them, (to make a limit in the number of training and test records or steps).

I've already hardcode it in the dataset file. I would like to know if there is a parameter or a better solution for that.

```
    def _generate_examples(self, filepath):
        """Yields examples."""
        with open(filepath, encoding="utf-8") as f:
            tsv_reader = csv.DictReader(f, delimiter="\t")
            idx = 0
            for example in tsv_reader:
                idx += 1 
                if "train" in filepath and idx > 4000:
                    break
                if ("test" in filepath or "val" in filepath) and idx > 1000:
                    break
```

**Comment by Timothyxxx** [comment]
If you want to control the examples of train set and dev set, what you did is right.
But if you want to train for less epoch or steps, you should change the hyper-parameter `num_train_epochs` and `max_steps`. For more questions, see trainer doc of huggingface in [here](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments).
