### ISSUE TITLE
Question on Prefix tuning code

### ISSUE THREAD

**Issue by base-y** [HKUNLP/UnifiedSKG#28]
Hi, I am looking at prefix tuning code..I have few queries on the implementation. 

1. what exactly are the variables in [these lines](https://github.com/HKUNLP/UnifiedSKG/blob/main/models/unified/prefixtuning.py#L52-L82)? I understand that prefix tuning provides input to every layer of the encoder-decoder model....But my understanding is that there should be a single wte and control_trans; not sure what the variables in the highlighted lines do.
2. I dont understand why the `*2` in [this line](https://github.com/HKUNLP/UnifiedSKG/blob/main/models/unified/prefixtuning.py#L82) of code?
3. What does the `control_trans` variable mean in [the code](https://github.com/HKUNLP/UnifiedSKG/blob/main/models/unified/prefixtuning.py#L53)? what is its function?
4. Also, I see another variable `mid_dim`. What is it conceptually?

Thank you

**Comment by ChenWu98** [comment]
Hi, Thanks for your interest!

Our prefix-tuning code is a cleaned-up version of Lisa's original implementation for BART. Answers to your questions are provided below, but we also recommend you look for more details in Lisa's implementation and paper.
1. Separate prefix is learned for each attention: encoder attention, decoder attention, and cross attention.
2. `*2` means the dimension of the attention key plus the dimension of the attention value.
3. `control_trans` is part of the re-parameterization trick introduced in Lisa's paper.
4. `mid_dim` is also part of the re-parameterization trick introduced in Lisa's paper.

**Comment by base-y** [comment]
Hi, thanks for the quick reply. So, I think `wte_enc` and `wte_dec` are part of the encoder self-attention and decoder self-attention parts. Can I know what is `wte`? is it a part of cross-attn or something else? the naming confused me.

**Comment by ChenWu98** [comment]
Yes, `wte` is for the cross-attention. We did not use "word initialization" for the prefix because they showed the benefits of such initialization under a low-data setting with only 100 samples. Actually, I am not sure, in Lisa's paper, whether this "word initialization" was used jointly with the re-parameterization trick or only used for the embedding-only ablation. If you have any ideas, please let me know!

Yes, we assume `num_encoder_layers == num_decoder_layers`. 

The permutation operation is used to make the tensor shape compatible with that of the key-value pairs.

**Comment by base-y** [comment]
Thanks, i am trying out word init.. Will let you know about its performance.

Also, I want to confirm what the avr metric does in the code? Is it averaging across tasks or averaging across different eval steps in a single task?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by base-y** [comment]
Thanks, can I know how to change the prefix tuning code to provide prefixes only to the first layer of encoder?

-------- Original Message --------
