### ISSUE TITLE
Help wanted! confused about the prefix_spider_with_cell_value.cfg in the T5-base configuration and T5-Large configuration.

### ISSUE THREAD

**Issue by kanseaveg** [HKUNLP/UnifiedSKG#44]
On [UnifiedSKG/configure/Salesforce/T5_base_prefix_spider_with_cell_value.cfg](https://github.com/xlang-ai/UnifiedSKG/blob/main/configure/Salesforce/T5_base_prefix_spider_with_cell_value.cfg)
It shows the `use_description=True` and `concatenate_description=True` 

But, on  [UnifiedSKG/configure/Salesforce/T5_large_prefix_spider_with_cell_value.cfg](https://github.com/xlang-ai/UnifiedSKG/blob/main/configure/Salesforce/T5_large_finetune_spider_with_cell_value.cfg)
It show the `use_description=False` and `concatenate_description=False`

Why are the settings different for different model bases when it comes to the same fine-tuning method? Did you write "t5-large" incorrectly?

**Comment by ChenWu98** [comment]
Hi, thanks for pointing this out! In our experiments, we did not find significant differences in terms of whether to finetune T5 with task descriptions or not, so hopefully this will not change our conclusion. We should have made it consistent, and sorry about the confusion!

**Comment by kanseaveg** [comment]
Thank you sincerely for your reply.
![image](https://github.com/xlang-ai/UnifiedSKG/assets/80022154/5505c085-6a79-4afc-a77c-cfec4729a838)
I raised this question because: taking spider as an example, when I reproduced the results of unified-skg, based on the configuration file, I couldn't determine whether to introduce description or knowledge. At least from the configuration file, I found that **neither description nor knowledge was introduced**. Therefore, when i reproduce the results in the paper is also biased low. If you have time, could you please help me check the configuration file? Just take spider configuration as an example. 
Thank you sincerely.
